sudo: false
addons:
  apt:
    packages:
      - oracle-java8-installer
language: java
jdk:
  - oraclejdk8
script: mvn -T 4 -Pcheck-duplicate,check-checkstyle,check-cycles,check-cpd,check-pmd,check-findbugs -Dmaven.test.skip=true verify #&& mvn -T 4 -Pcheck-cobertura-integration-test,attach-integration-test cobertura:check-integration-test
after_success:
  - mvn -T 4 -Pattach-integration-test cobertura:cobertura-integration-test org.eluder.coveralls:coveralls-maven-plugin:4.2.0:report
cache:
  directories:
  - $HOME/.m2
